image: node:14

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build_app:
  stage: build
  script:
    - npm install

serve_app:
  stage: test
  script:
    - ng serve --host 0.0.0.0
  artifacts:
    paths:
      - dist/
  only:
    - master
